plugins:
  mitt_plugin_outlet_locations_enabled:
    default: false
    client: true

mitt_outlets:
  mitt_show_admin_menu_enabled:
    default: true
    client: true
  mitt_show_admin_dashboard_top_enabled:
    default: true
    client: true
  
  mitt_show_above_footer_enabled:
    default: true
    client: true
  mitt_show_below_footer_enabled:
    default: true
    client: true
  mitt_show_composer_open_enabled:
    default: true
    client: true
  mitt_show_composer_fields_enabled:
    default: true
    client: true
  mitt_show_composer_fields_below_enabled:
    default: true
    client: true
  mitt_show_discovery_list_container_top_enabled:
    default: true
    client: true
  mitt_show_discovery_below_enabled:
    default: true
    client: true
  mitt_show_full_page_search_category_enabled:
    default: true
    client: true
#   mitt_show_header_after_home_logo_enabled:
#     default: true
#     client: true
#   mitt_show_header_before_notifications_enabled:
#     default: true
#     client: true
#   mitt_show_header_notifications_enabled:
#     default: true
#     client: true
#   mitt_show_header_before_dropdowns_enabled:
#     default: true
#     client: true
#   mitt_show_header_under_content_enabled:
#     default: true
#     client: true
  mitt_show_above_static_enabled:
    default: true
    client: true
  mitt_show_topic_above_post_stream_enabled:
    default: true
    client: true
  mitt_show_edit_topic_enabled:
    default: true
    client: true
  mitt_show_topic_title_enabled:
    default: true
    client: true
  mitt_show_topic_above_posts_enabled:
    default: true
    client: true
  mitt_show_topic_above_suggested_enabled:
    default: true
    client: true
  mitt_show_topic_admin_menu_buttons_enabled:
    default: true
    client: true
  mitt_show_user_card_metadata_enabled:
    default: true
    client: true
  mitt_show_user_card_post_names_enabled:
    default: true
    client: true

  mitt_show_bread_crumbs_right_enabled:
    default: true
    client: true
  mitt_show_category_custom_settings_enabled:
    default: true
    client: true
#   mitt_show_hamburger_admin_enabled:
#     default: true
#     client: true
#   mitt_show_site_map_links_enabled:
#     default: true
#     client: true
#   mitt_show_site_map_links_last_enabled:
#     default: true
#     client: true
#   mitt_show_above_search_enabled:
#     default: true
#     client: true
#   mitt_show_search_category_enabled:
#     default: true
#     client: true
  mitt_show_user_stream_item_header_enabled:
    default: true
    client: true
  mitt_show_topic_category_enabled:
    default: true
    client: true
#   mitt_show_user_menu_bottom_enabled:
#     default: true
#     client: true

  mitt_show_l_topic_list_tags_enabled:
    default: true
    client: true
  mitt_show_l_topic_list_after_title_enabled:
    default: true
    client: true
  
  mitt_show_ml_topic_list_tags_enabled:
    default: true
    client: true
  
  mitt_show_create_account_before_password_enabled:
    default: true
    client: true
  mitt_show_post_revisions_enabled:
    default: true
    client: true

  mitt_show_user_activity_bottom_enabled:
    default: true
    client: true
  mitt_show_user_custom_controls_enabled:
    default: true
    client: true
  mitt_show_user_custom_preferences_enabled:
    default: true
    client: true
  mitt_show_user_profile_controls_enabled:
    default: true
    client: true
  mitt_show_user_profile_public_fields_enabled:
    default: true
    client: true
  mitt_show_user_profile_primary_enabled:
    default: true
    client: true
  mitt_show_user_profile_secondary_enabled:
    default: true
    client: true